apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-04-06T20:31:56Z"
  generation: 1
  labels:
    run: hackunt-server
  name: hackunt-server
  namespace: default
  resourceVersion: "5776"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/hackunt-server
  uid: 05a3cfa7-58ab-11e9-839f-42010a80007e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: hackunt-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hackunt-server
    spec:
      containers:
      - image: robotlaserbeam/hackunt-server
        imagePullPolicy: Always
        name: hackunt-server
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-04-06T20:31:56Z"
    lastUpdateTime: "2019-04-06T20:31:59Z"
    message: ReplicaSet "hackunt-server-7767d6fb69" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-04-06T20:40:47Z"
    lastUpdateTime: "2019-04-06T20:40:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
